name: Deploy Infrastructure with Terraform

# on:
#   push:
#     branches:
#       - main  # Trigger on pushes to the main branch
#   pull_request:
#     branches:
#       - main  # Trigger on pull requests to the main branch

on:
  workflow_dispatch: # Allows manual trigger
    inputs:
      action: # Define an input to choose between "apply" and "destroy"
        description: "Choose action: apply or destroy"
        required: true
        default: "apply" # Default is "apply"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6  # Specify your Terraform version

    # Step 3: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Specify your region

    # Step 4: Terraform Init
    - name: Initialize Terraform
      run: terraform init

    # # Step 5: Terraform Plan
    # - name: Terraform Plan
    #   run: terraform plan -out=tfplan

    # Step 5: Terraform Plan
    - name: Terraform Plan
      if: github.event.inputs.action == 'apply' || github.event.inputs.action == 'destroy'
      run: |
        if [[ "${{ github.event.inputs.action }}" == "apply" ]]; then
          terraform plan -out=tfplan
        elif [[ "${{ github.event.inputs.action }}" == "destroy" ]]; then
          terraform plan -destroy -out=tfplan
        fi

    # Step 6: Terraform Apply
    - name: Terraform Apply
      if: github.event_name == 'push'  # Only apply on pushes, not pull requests
      run: terraform apply -auto-approve tfplan

    # Step 7: Terraform Destroy
    - name: Terraform Destroy
      if: github.event.inputs.action == 'destroy'
      run: terraform apply -auto-approve tfplan